# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 23:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(default=datetime.datetime(2017, 3, 15, 23, 35, 6, 828425))),
                ('series', models.IntegerField(default=0)),
            ],
        ),
    ]
