# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 23:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 15, 23, 37, 1, 354830)),
        ),
    ]
