# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('c_app', '0003_auto_20170315_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_and_time',
            new_name='ends',
        ),
        migrations.RemoveField(
            model_name='event',
            name='series',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Event', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='starts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
