# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 23:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_app', '0006_auto_20170317_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ends',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='starts',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
