# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 23:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_app', '0007_auto_20170317_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ends',
        ),
        migrations.RemoveField(
            model_name='event',
            name='starts',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Start Time'),
        ),
    ]
